"""Initial migration

Revision ID: e788f6fdb4bb
Revises: 
Create Date: 2024-11-07 08:01:26.477156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e788f6fdb4bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet',
    sa.Column('diet_id', sa.Integer(), nullable=False),
    sa.Column('diet_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('diet_id')
    )
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('overall_rating', sa.DECIMAL(), nullable=True),
    sa.Column('vegan_rating', sa.DECIMAL(), nullable=True),
    sa.Column('gluten_free_rating', sa.DECIMAL(), nullable=True),
    sa.Column('vegetarian_rating', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pass_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('pass_token', sa.String(length=255), nullable=True),
    sa.Column('pass_token_valid_till', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.DECIMAL(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('user_preference',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.diet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'diet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    op.drop_table('review')
    op.drop_table('user')
    op.drop_table('restaurant')
    op.drop_table('diet')
    # ### end Alembic commands ###
