# Use the official Python image from Docker Hub
FROM python:3.9-slim

# Set work directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app

# Set environment variables for Flask development
ENV FLASK_APP=run.py
ENV FLASK_ENV=development

# Expose port 5000 for Flask
EXPOSE 5000

# Run the Flask development server
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
