import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
// src/pages/Contact.tsx
import { FaFacebookF, FaInstagram, FaTwitter } from 'react-icons/fa';
import Footer from '../components/Footer';
import Header from '../components/Header';
function Contact() {
    return (_jsxs(_Fragment, { children: [_jsx(Header, {}), _jsx("main", { className: "flex flex-col items-center mt-20 px-4", children: _jsxs("section", { className: "max-w-4xl w-full py-16", children: [_jsx("h1", { className: "text-4xl font-bold mb-8 text-center", children: "Contact Us" }), _jsx("div", { className: "flex flex-wrap md:flex-nowrap md:space-x-8", children: _jsxs("div", { className: "w-full", children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: "Get in Touch" }), _jsx("p", { className: "mb-4 text-gray-700", children: "We'd love to hear from you! Whether you have a question about features, pricing, or anything else, our team is ready to answer all your questions." }), _jsxs("ul", { className: "space-y-6 text-gray-700", children: [_jsxs("li", { children: [_jsx("strong", { className: "block text-lg", children: "Address" }), _jsxs("p", { children: ["123 Main Street", _jsx("br", {}), "Boston, MA 02115"] })] }), _jsxs("li", { children: [_jsx("strong", { className: "block text-lg", children: "Email" }), _jsx("a", { href: "mailto:support@menumatch.com", className: "text-red-500 hover:underline", children: "support@menumatch.com" })] }), _jsxs("li", { children: [_jsx("strong", { className: "block text-lg", children: "Phone" }), _jsx("a", { href: "tel:+1234567890", className: "text-red-500 hover:underline", children: "+1 (234) 567-890" })] })] }), _jsxs("div", { className: "mt-8", children: [_jsx("h3", { className: "text-lg font-semibold mb-2", children: "Follow Us" }), _jsxs("div", { className: "flex space-x-4", children: [_jsx("a", { href: "#", "aria-label": "Facebook", className: "text-gray-700 hover:text-red-500", children: _jsx(FaFacebookF, { className: "w-6 h-6" }) }), _jsx("a", { href: "#", "aria-label": "Twitter", className: "text-gray-700 hover:text-red-500", children: _jsx(FaTwitter, { className: "w-6 h-6" }) }), _jsx("a", { href: "#", "aria-label": "Instagram", className: "text-gray-700 hover:text-red-500", children: _jsx(FaInstagram, { className: "w-6 h-6" }) })] })] })] }) })] }) }), _jsx(Footer, {})] }));
}
export default Contact;
