# Dockerfile for Development
FROM node:20

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and yarn.lock
COPY package.json ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose the development port
EXPOSE 5173

# Start the development server
CMD ["yarn", "dev"]